In [281]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.neighbors import NearestNeighbors
import joblib

In [282]:
df = pd.read_csv('car_details.csv')

In [283]:
df.info()
df[0:10]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
7,Tata Indigo Grand Petrol,2014,240000,60000,Petrol,Individual,Manual,Second Owner
8,Hyundai Creta 1.6 VTVT S,2015,850000,25000,Petrol,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner

In [284]:
df.shape

(4340, 8)

In [285]:
mean_prices = df.groupby('name')['selling_price'].mean().round(2)

In [286]:
df['selling_price'] = df['name'].map(mean_prices)

In [287]:
df= df.drop_duplicates(subset='name').reset_index(drop=True)

In [288]:
df.shape

(1491, 8)

In [289]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,94347.83,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,144416.67,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,490666.40,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,229999.86,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,530555.56,141000,Diesel,Individual,Manual,Second Owner

In [290]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1491 entries, 0 to 1490
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           1491 non-null   object
 1   year           1491 non-null   int64
 2   selling_price  1491 non-null   float64
 3   km_driven      1491 non-null   int64
 4   fuel           1491 non-null   object
 5   seller_type    1491 non-null   object
 6   transmission   1491 non-null   object
 7   owner          1491 non-null   object
dtypes: float64(1), int64(2), object(5)
memory usage: 93.3+ KB

In [291]:
df['year'].value_counts()

year
2017    163
2018    151
2015    133
2012    127
2014    118
2016    112
2013    103
2011     99
2019     85
2009     74
2010     73
2007     58
2006     42
2008     40
2020     31
2005     24
2004     14
2002     12
2003      9
2001      7
2000      5
1998      4
1999      4
1996      1
1995      1
1997      1
Name: count, dtype: int64

In [292]:
df['year'].sort_values(ascending=False)

1481    2020
889     2020
1055    2020
1016    2020
769     2020
        ...
1049    1998
990     1998
1346    1997
46      1996
409     1995
Name: year, Length: 1491, dtype: int64

In [293]:
df['year'] +=3

In [294]:
df['year'].sort_values(ascending=False)

1481    2023
889     2023
1055    2023
1016    2023
769     2023
        ...
1049    2001
990     2001
1346    2000
46      1999
409     1998
Name: year, Length: 1491, dtype: int64

In [295]:
df.info()
df[0:10]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1491 entries, 0 to 1490
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           1491 non-null   object
 1   year           1491 non-null   int64
 2   selling_price  1491 non-null   float64
 3   km_driven      1491 non-null   int64
 4   fuel           1491 non-null   object
 5   seller_type    1491 non-null   object
 6   transmission   1491 non-null   object
 7   owner          1491 non-null   object
dtypes: float64(1), int64(2), object(5)
memory usage: 93.3+ KB

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2010,94347.83,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2010,144416.67,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2015,490666.40,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2020,229999.86,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2017,530555.56,141000,Diesel,Individual,Manual,Second Owner
5,Maruti Alto LX BSIII,2010,117500.00,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2019,430000.00,25000,Petrol,Individual,Manual,First Owner
7,Tata Indigo Grand Petrol,2017,245000.00,60000,Petrol,Individual,Manual,Second Owner
8,Hyundai Creta 1.6 VTVT S,2018,862500.00,25000,Petrol,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2020,365000.00,78000,CNG,Individual,Manual,First Owner

In [296]:
df = df.drop(['seller_type','transmission','owner'],axis=1)

In [297]:
df[0:10]

                        name  year  selling_price  km_driven    fuel
0              Maruti 800 AC  2010       94347.83      70000  Petrol
1   Maruti Wagon R LXI Minor  2010      144416.67      50000  Petrol
2       Hyundai Verna 1.6 SX  2015      490666.40     100000  Diesel
3     Datsun RediGO T Option  2020      229999.86      46000  Petrol
4      Honda Amaze VX i-DTEC  2017      530555.56     141000  Diesel
5       Maruti Alto LX BSIII  2010      117500.00     125000  Petrol
6  Hyundai Xcent 1.2 Kappa S  2019      430000.00      25000  Petrol
7   Tata Indigo Grand Petrol  2017      245000.00      60000  Petrol
8   Hyundai Creta 1.6 VTVT S  2018      862500.00      25000  Petrol
9   Maruti Celerio Green VXI  2020      365000.00      78000     CNG

In [298]:
df['company'] = df['name'].str.split(' ').str.get(0)

In [299]:
df[0:10]

                        name  year  selling_price  km_driven    fuel  company
0              Maruti 800 AC  2010       94347.83      70000  Petrol   Maruti
1   Maruti Wagon R LXI Minor  2010      144416.67      50000  Petrol   Maruti
2       Hyundai Verna 1.6 SX  2015      490666.40     100000  Diesel  Hyundai
3     Datsun RediGO T Option  2020      229999.86      46000  Petrol   Datsun
4      Honda Amaze VX i-DTEC  2017      530555.56     141000  Diesel    Honda
5       Maruti Alto LX BSIII  2010      117500.00     125000  Petrol   Maruti
6  Hyundai Xcent 1.2 Kappa S  2019      430000.00      25000  Petrol  Hyundai
7   Tata Indigo Grand Petrol  2017      245000.00      60000  Petrol     Tata
8   Hyundai Creta 1.6 VTVT S  2018      862500.00      25000  Petrol  Hyundai
9   Maruti Celerio Green VXI  2020      365000.00      78000     CNG   Maruti

In [300]:
df.rename(columns={
    'fuel': 'fuel_type',
    'selling_price': 'predicted_price',
    'km_driven': 'kilo_driven'
}, inplace=True)

In [301]:
df[0:10]

,name,year,predicted_price,kilo_driven,fuel_type,company
0,Maruti 800 AC,2010,94347.83,70000,Petrol,Maruti
1,Maruti Wagon R LXI Minor,2010,144416.67,50000,Petrol,Maruti
2,Hyundai Verna 1.6 SX,2015,490666.40,100000,Diesel,Hyundai
3,Datsun RediGO T Option,2020,229999.86,46000,Petrol,Datsun
4,Honda Amaze VX i-DTEC,2017,530555.56,141000,Diesel,Honda
5,Maruti Alto LX BSIII,2010,117500.00,125000,Petrol,Maruti
6,Hyundai Xcent 1.2 Kappa S,2019,430000.00,25000,Petrol,Hyundai
7,Tata Indigo Grand Petrol,2017,245000.00,60000,Petrol,Tata
8,Hyundai Creta 1.6 VTVT S,2018,862500.00,25000,Petrol,Hyundai
9,Maruti Celerio Green VXI,2020,365000.00,78000,CNG,Maruti

In [302]:
df.to_csv('Recommendation_Data.csv')

In [303]:
categorical_features = ['fuel_type', 'company']
numerical_features = ['year', 'predicted_price', 'kilo_driven']

In [304]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),
        ('cat', OneHotEncoder(), categorical_features)
    ])

In [305]:
car_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('knn', NearestNeighbors(n_neighbors=5, algorithm='auto'))  # Adjust n_neighbors as needed
])

In [306]:
df1 = pd.read_csv('C:\\Users\\aryaman.kanwar\\CarSmartz\\cmz_car.csv')

In [307]:
df1[0:20]

,id,company,car_model,year,fuel_type,kilo_driven,predicted_price
0,1,Honda,Honda Amaze 1.2,2019,Petrol,8000,557945.87
1,2,Ford,Ford EcoSport Titanium,2015,Petrol,170000,249405.84
2,3,Maruti,Maruti Suzuki Dzire,2015,Petrol,100000,233701.08
3,4,Hyundai,Hyundai Creta 1.6,2020,Petrol,30000,957310.39
4,5,Tata,Tata Tiago Revotorq,2018,Diesel,50000,231273.99
5,6,Honda,Honda City,2011,Petrol,102000,175226.54
6,7,Chevrolet,Chevrolet Cruze LTZ,2014,Petrol,40000,106429.93
7,8,Chevrolet,Chevrolet Cruze LTZ,2014,Petrol,57000,106429.93
8,9,Datsun,Datsun Redi GO,2018,LPG,3415135,341859.19
9,10,Maruti,Maruti 800 AC,2010,Petrol,70000,94347.83
10,11,Maruti,Maruti Wagon R LXI Minor,2010,Petrol,50000,144416.67
11,12,Hyundai,Hyundai Verna 1.6 SX,2015,Diesel,100000,490666.40
12,13,Datsun,Datsun RediGO T Option,2020,Petrol,46000,229999.86
13,14,Honda,Honda Amaze VX i-DTEC,2017,Diesel,141000,530555.56
14,15,Maruti,Maruti Alto LX BSIII,2010,Petrol,125000,117500.00
15,16,Hyundai,Hyundai Xcent 1.2 Kappa S,2019,Petrol,25000,430000.00
16,17,Tata,Tata Indigo Grand Petrol,2017,Petrol,60000,245000.00
17,18,Hyundai,Hyundai Creta 1.6 VTVT S,2018,Petrol,25000,862500.00
18,19,Maruti,Maruti Celerio Green VXI,2020,CNG,78000,365000.00
19,20,Chevrolet,Chevrolet Sail 1.2 Base,2018,Petrol,35000,248000.00

In [308]:
car_pipeline.fit(df1)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', 'passthrough',
                                                  ['year', 'predicted_price',
                                                   'kilo_driven']),
                                                 ('cat', OneHotEncoder(),
                                                  ['fuel_type', 'company'])])),
                ('knn', NearestNeighbors())])

In [309]:
def recommend_similar_cars(car_model):
    # Check if the car model exists in the DataFrame
    if car_model not in df1['car_model'].values:
        print(f"Car model '{car_model}' not found in the dataset.")
        return pd.DataFrame()  # Return an empty DataFrame if not found
    
    # Get the index of the specified car model
    car_index = df1[df1['car_model'] == car_model].index[0]
    
    # Transform the features of the selected car using the preprocessor
    car_features = car_pipeline.named_steps['preprocessor'].transform(df1.iloc[[car_index]])
    
    # Get similar cars based on the selected car's index
    distances, indices = car_pipeline.named_steps['knn'].kneighbors(car_features)
    
    # Extract the similar cars and drop unnecessary columns
    similar_cars = df1.iloc[indices[0]].drop(columns=['year', 'predicted_price', 'kilo_driven', 'fuel_type', 'company']).reset_index(drop=True)
    
    return similar_cars

In [310]:
recommended_cars = recommend_similar_cars('Honda Amaze 1.2')
print(recommended_cars)

     id                                car_model
0     1                          Honda Amaze 1.2
1   324                    Tata Tiago NRG Petrol
2   454                    Honda Amaze SX i-VTEC
3   308                    Maruti Swift VXI BSIV
4  1290  Hyundai Elite i20 Petrol Magna Exective

In [311]:
import pickle

In [312]:
with open('car_recommendation_model.pkl', 'wb') as f:
    pickle.dump(car_pipeline, f)